export enum ErrorCode {
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',

    META_API_ERROR = 'META_API_ERROR',
    META_PERMISSION_DENIED = 'META_PERMISSION_DENIED',
    META_RATE_LIMITED = 'META_RATE_LIMITED',
    META_TOKEN_EXPIRED = 'META_TOKEN_EXPIRED',
    META_TOKEN_INVALID = 'META_TOKEN_INVALID',
    META_RESOURCE_NOT_FOUND = 'META_RESOURCE_NOT_FOUND',
    META_BUSINESS_NOT_VERIFIED = 'META_BUSINESS_NOT_VERIFIED',

    CONFIG_MISSING = 'CONFIG_MISSING',
    CONFIG_INVALID = 'CONFIG_INVALID',
}
